##############################################################
########################    Figure 3,S5,S6   #######################
##############################################################

########################## Note ##############################
## Using 'here' package for path management.
## Root directory is set to: code_and_data
##############################################################

if (!requireNamespace("openxlsx", quietly = TRUE)) install.packages("openxlsx")
library(openxlsx)
library(here) # Load here package
options(stringsAsFactors = FALSE)

# Modification: Use here() to point to the data directory relative to code_and_data
current_file <- here("RealData", "Total Sample","result_data", "Result_ground_truth")


dataset_folders <- c("luad", "pbmc", "mescs", "mouse liver", "mouse uterus")
datasets        <- c("LUAD", "PBMC", "mESCs", "Mouse Liver", "Mouse Uterus")


networks <- c("CORUM", "PPI(F)", "PPI(P)", "PerturbAtlas") 
network_files <- c("corum.xlsx", "ppi_fun.xlsx", "ppi_phy.xlsx", "Perturb-seq.xlsx")

names(network_files) <- networks


methods <- c("JRDNN-KM", "BLGGM", "JGNsc", "JSEM", "SPqN",
             "Normalisr", "GENIE3", "locCSN", "CS-CORE")


safe_numeric <- function(x) {
  if (is.factor(x)) x <- as.character(x)
  if (is.character(x)) {
    x <- trimws(x)
    x[x %in% c("", "NA", "NaN")] <- NA_character_
  }
  suppressWarnings(as.numeric(x))
}

pull_metric <- function(path, metric) {
  if (!file.exists(path)) return(NULL)
  df <- tryCatch(read.xlsx(path), error = function(e) NULL)
  if (is.null(df)) return(NULL)
  cn <- tolower(colnames(df))
  method_col <- which(cn == "method")
  metric_col <- which(cn == tolower(metric))
  if (!length(method_col) || !length(metric_col)) return(NULL)
  m <- as.character(df[[method_col[1]]])
  v <- safe_numeric(df[[metric_col[1]]])
  names(v) <- m
  v[is.finite(v)]
}


build_array <- function(metric) {
  arr <- array(NA_real_,
               dim = c(length(methods), length(networks), length(datasets)),
               dimnames = list(methods, networks, datasets))
  for (k in seq_along(dataset_folders)) {
    fold <- dataset_folders[k]
    for (j in seq_along(network_files)) {
      # file.path works perfectly combined with the path string generated by here()
      p <- file.path(current_file, fold, network_files[j])
      v <- pull_metric(p, metric)
      if (length(v)) {
        common <- intersect(names(v), methods)
        arr[common, names(network_files)[j], datasets[k]] <- v[common]
      }
    }
  }
  arr
}


f1_array        <- build_array("F1")
recall_array    <- build_array("Recall")
precision_array <- build_array("Precision")

methods <- c("JRDNN-KM", "BLGGM", "JGNsc", "JSEM", "SpQN",
             "Normalisr", "GENIE3", "locCSN", "CS-CORE")


plot_metric_array <- function(metric_array, metric_name) {
  mean_metric <- apply(metric_array, c(1, 3), mean)  
  
  
  
  n_col <- length(datasets)
  layout_matrix <- matrix(c(1:n_col, rep(n_col+1, n_col)), 
                          nrow = 2, byrow = TRUE)
  layout(layout_matrix, heights = c(0.55, 0.45))  
  
  
  par(oma = c(3, 3, 0, 1),  
      mar = c(2, 5, 1.5, 1)) 
  
  method_pch <- c(15, 16, 17, 18, 0, 1, 2, 5, 8)
  net_colors <- c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3")
  
  
  if (metric_name=='F1 Score'){
    y_max=0.8
  } else if (metric_name=='Recall'){
    y_max=0.9
  } else 
  {y_max=0.9
  
  }
  
  
  for (i in seq_along(datasets)) {
    plot_data <- as.data.frame.table(metric_array[,, datasets[i]])
    colnames(plot_data) <- c("Method", "Network", "F1")
    
    plot(1, type = "n", xlim = c(0.5, 9.5), ylim = c(0, y_max),
         xlab = "", ylab = ifelse(i == 1, metric_name, ""),  
         xaxt = "n", main = datasets[i],cex.main = 1.5,   
         cex.lab = 1.5,cex.axis = 1.4)
    
    abline(h = seq(0.2, 0.8, by = 0.2), col = "gray90", lty = 3)
    
    for (net in seq_along(networks)) {
      subset_data <- plot_data[plot_data$Network == networks[net], ]
      points(x = as.numeric(subset_data$Method), 
             y = subset_data$F1,
             pch = method_pch,
             col = net_colors[net],
             cex = 1.2)
    }
    
    
    for (j in seq_along(methods)) {
      mean_value <-mean_metric[j, i]
      segments(x0 = j - 0.4, 
               x1 = j + 0.4,
               y0 = mean_value, 
               y1 = mean_value,
               col = "red", lwd = 3, lty = 1)
    }
    
    axis(1, at = 1:9, labels = methods, las = 2, cex.axis = 1)
  }
  
  
  
  plot(1, type = "n", axes = FALSE, xlab = "", ylab = "")
  legend("top", 
         legend = c("Network Types:", networks, "Mean (red line)"),
         col = c(NA, net_colors, "red"),
         pch = c(NA, rep(15, 4), NA),
         lty = c(NA, rep(NA, 4), 1),
         lwd = c(NA, rep(NA, 4), 3),
         title = NULL,
         bty = "n", 
         cex = 1.1,
         horiz = TRUE,
         xpd = NA,
         x.intersp = 0.3,            
         y.intersp = 0.8,              
         text.width = NULL,           
         seg.len = 1.5,
         inset = c(0, 0.15)
  )
  
  
}


plot_metric_array(f1_array,        "F1 Score")
plot_metric_array(recall_array,    "Recall")
plot_metric_array(precision_array, "Precision")
